# Generated by Django 6.1.1 on 2026-09-24 11:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('administrateur', 'Administrateur'), ('enseignant', 'Enseignant'), ('apprenant', 'Apprenant')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id_ressource', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('type_ressource', models.CharField(choices=[('quiz', 'Quiz'), ('video', 'Vidéo'), ('document', 'Document')], max_length=20)),
                ('niveau_requis', models.CharField(choices=[('debutant', 'Débutant'), ('moyen', 'Moyen'), ('excellent', 'Excellent')], default='moyen', help_text="Niveau d'apprenant auquel cette ressource est adaptée (utilisé par le moteur de recommandation).", max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Espace',
            fields=[
                ('id_espace', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Espace',
                'verbose_name_plural': 'Espaces',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id_etab', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('localite', models.CharField(max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id_question', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enonce', models.TextField()),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil_administrateur', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrateur',
                'verbose_name_plural': 'Administrateurs',
            },
        ),
        migrations.CreateModel(
            name='Apprenant',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil_apprenant', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('moyen', 'Moyen'), ('excellent', 'Excellent')], default='debutant', help_text='Groupe attribué par le regroupement K-means (débutant / moyen / excellent).', max_length=20)),
            ],
            options={
                'verbose_name': 'Apprenant',
                'verbose_name_plural': 'Apprenants',
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil_enseignant', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matiere_principale', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('ressource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='document', serialize=False, to='plateforme_edu.ressource')),
                ('fichier', models.FileField(blank=True, default='', upload_to='documents/')),
                ('nombre_pages', models.PositiveIntegerField(default=0)),
                ('indexe', models.BooleanField(default=False, help_text="Vrai si le document a été découpé et indexé pour l'assistant IA.")),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('ressource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='quiz', serialize=False, to='plateforme_edu.ressource')),
                ('nombre_questions', models.PositiveIntegerField(default=0)),
                ('duree_minutes', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('ressource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='video', serialize=False, to='plateforme_edu.ressource')),
                ('fichier', models.FileField(blank=True, default='', upload_to='videos/')),
                ('duree_secondes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
            },
        ),
        migrations.AddField(
            model_name='ressource',
            name='espace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='plateforme_edu.espace'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='plateforme_edu.etablissement'),
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id_parcours', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='plateforme_edu.etablissement')),
            ],
            options={
                'verbose_name': 'Parcours',
                'verbose_name_plural': 'Parcours',
                'ordering': ['intitule'],
            },
        ),
        migrations.AddField(
            model_name='espace',
            name='parcours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espaces', to='plateforme_edu.parcours'),
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id_choix', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texte', models.CharField(max_length=255)),
                ('est_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='plateforme_edu.question')),
            ],
            options={
                'verbose_name': 'Choix',
                'verbose_name_plural': 'Choix',
            },
        ),
        migrations.CreateModel(
            name='Statistiques',
            fields=[
                ('id_stat', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moyenne_generale', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nombre_quiz_passes', models.PositiveIntegerField(default=0)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('apprenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='plateforme_edu.apprenant')),
            ],
            options={
                'verbose_name': 'Statistiques',
                'verbose_name_plural': 'Statistiques',
            },
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id_recommandation', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groupe', models.CharField(blank=True, help_text='Groupe attribué par le regroupement (ex : débutant, moyen, excellent).', max_length=50)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='plateforme_edu.ressource')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='plateforme_edu.apprenant')),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='AssistanteIA',
            fields=[
                ('id_echange', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_joint', models.FileField(blank=True, help_text="Document importé directement dans la conversation (bouton « + »), pour que l'assistant l'utilise dans sa réponse.", null=True, upload_to='documents_ia/')),
                ('question', models.TextField()),
                ('reponse', models.TextField()),
                ('modele_utilise', models.CharField(blank=True, max_length=50)),
                ('temps_reponse_secondes', models.FloatField(blank=True, help_text="Durée entre l'envoi de la question et la réponse complète (recherche RAG + génération) — utile pour comparer les performances entre machines (ex : ordinateur de dev vs Raspberry Pi).", null=True)),
                ('date_echange', models.DateTimeField(auto_now_add=True)),
                ('ressource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echanges_ia', to='plateforme_edu.ressource')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echanges_ia', to='plateforme_edu.apprenant')),
            ],
            options={
                'verbose_name': 'Échange assistant IA',
                'verbose_name_plural': 'Échanges assistant IA',
                'ordering': ['-date_echange'],
            },
        ),
        migrations.AddField(
            model_name='ressource',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources_publiees', to='plateforme_edu.enseignant'),
        ),
        migrations.CreateModel(
            name='SegmentDocument',
            fields=[
                ('id_segment', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texte', models.TextField()),
                ('embedding', models.JSONField()),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='plateforme_edu.document')),
            ],
            options={
                'verbose_name': 'Segment de document',
                'verbose_name_plural': 'Segments de document',
                'ordering': ['document', 'ordre'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='plateforme_edu.quiz'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id_evaluation', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_passage', models.DateTimeField(auto_now_add=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='plateforme_edu.apprenant')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='plateforme_edu.quiz')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-date_passage'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id_inscription', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='plateforme_edu.parcours')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='plateforme_edu.apprenant')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_inscription'],
                'unique_together': {('apprenant', 'parcours')},
            },
        ),
    ]
