# Generated by Django 5.2.17 on 2026-09-24 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plateforme_edu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ressource",
            name="matiere",
            field=models.CharField(
                blank=True,
                help_text="Matière de la ressource (ex : Mathématiques, Anglais...). Surtout utile pour les ressources nationales, sans espace/parcours pour les classer.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="ressource",
            name="source_externe",
            field=models.URLField(
                blank=True,
                help_text="URL de la source d'origine, pour une ressource nationale importée (ex : bibliothèque numérique du MEN). Vide pour une ressource déposée par un enseignant.",
            ),
        ),
        migrations.AlterField(
            model_name="ressource",
            name="espace",
            field=models.ForeignKey(
                blank=True,
                help_text="Laisser vide pour une ressource nationale par défaut (ex : bibliothèque numérique du MEN), accessible à tout apprenant même sans établissement rattaché.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ressources",
                to="plateforme_edu.espace",
            ),
        ),
    ]
