# Generated by Django 6.1.1 on 2026-09-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme_edu', '0006_ressource_matiere_ressource_source_externe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistanteia',
            name='conversation_id',
            field=models.UUIDField(blank=True, db_index=True, help_text="Regroupe les échanges d'une même conversation (même valeur tant que l'apprenant ne clique pas sur « Nouvelle conversation »).", null=True),
        ),
    ]
