# Generated by Django 6.1.1 on 2026-09-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme_edu', '0007_assistanteia_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistiques',
            name='degre_debutant',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Pourcentage d'appartenance au groupe débutant (méthode floue).", max_digits=5),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='degre_excellent',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Pourcentage d'appartenance au groupe excellent (méthode floue).", max_digits=5),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='degre_moyen',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Pourcentage d'appartenance au groupe moyen (méthode floue).", max_digits=5),
        ),
    ]
