# Generated by Django 6.1.1 on 2026-09-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme_edu', '0009_etablissement_code_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='code_inscription',
            field=models.CharField(blank=True, editable=False, help_text="Code à communiquer aux apprenants pour qu'ils puissent s'inscrire dans cet établissement.", max_length=8, unique=True),
        ),
    ]
