services:
  # --- Nouveau service Réseau ---
  wifi:
    build: ./reseau
    container_name: memoire_wifi
    network_mode: "host" # INDISPENSABLE : donne au conteneur l'accès direct à la carte Wi-Fi
    privileged: true     # Nécessaire pour piloter le matériel physique
    volumes:
      - ./reseau/hostapd.conf:/etc/hostapd/hostapd.conf
      - ./reseau/dnsmasq.conf:/etc/dnsmasq.conf
    restart: always

# --- Service n°2 : La Base de Données ---

  db:

    image: mysql:8.0 # Télécharge l'image officielle MySQL ver>

    container_name: memoire_db # Nomme le conteneur pour le re>

    restart: always # Redémarre automatiquement le serveur si >

    environment: # Définit les variables de configuration de M>

      MYSQL_DATABASE: plateforme_db # Crée automatiquement la >

      MYSQL_ROOT_PASSWORD: alima # Définit ton mot de passe ad>

    volumes: # Zone de stockage persistante

      - ./base_donnees:/var/lib/mysql # Lie le dossier local a>



  # --- Service n°3 : L'Application Django ---

  web:

    build: ./app # Dit à Docker de construire l'image à partir>

    container_name: memoire_app # Nom du conteneur de ton appl>

    volumes: # Synchronisation en temps réel du code

      - ./app:/app # Permet de modifier le code sur Windows et>

    ports: # Redirection des ports

      - "8000:8000" # Relie le port 8000 du conteneur au port >

    depends_on: # Gestion de l'ordre de démarrage

      - db # L'application attend que la base de données soit >

    environment: # Transmet les accès à Django via des variabl>

      - DB_NAME=plateforme_db # Nom de la base à rejoindre

      - DB_USER=root # Utilisateur SQL

      - DB_PASSWORD=alima # Ton mot de passe sécurisé

      - DB_HOST=db # Utilise le nom du service "db" comme adre>


