version: "3.8"

services:
  wifi:
    build: ./reseau
    container_name: memoire_wifi
    network_mode: "host"
    privileged: true
    volumes:
      - ./reseau/hostapd.conf:/etc/hostapd/hostapd.conf
      - ./reseau/dnsmasq.conf:/etc/dnsmasq.conf
    restart: always

  db:
    image: arm64v8/mariadb:10.11
    platform: linux/arm64
    container_name: memoire_db
    restart: always
    environment:
      MYSQL_DATABASE: plateforme_db
      MYSQL_ROOT_PASSWORD: alima
    volumes:
      - ./base_donnees:/var/lib/mysql

  ollama:
    image: ollama/ollama:latest
    container_name: memoire_ia
    platform: linux/arm64
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: always

  web:
    build: ./app
    container_name: memoire_app
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./app:/app
      - /usr/local/lib/python3.11/site-packages/
      - /usr/local/bin/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ollama
    environment:
      DB_NAME: plateforme_db
      DB_USER: root
      DB_PASSWORD: alima
      DB_HOST: db
    command: sh -c "pip install requests && python manage.py runserver 0.0.0.0:8000"