#Interface sur laquelle dnsmasq va écouter (ex: wlan0 pour le Wi-Fi)
bind-interfaces
#interface=wlan0 

# Plage d'adresses IP à distribuer aux élèves (de .10 à .50)
dhcp-range=192.168.1.10,192.168.1.50,12h

# Rediriger un nom de domaine local vers ton application Django
# Remplace 192.168.1.1 par l'adresse IP de ton PC
address=/monespace.sn/192.168.1.1
