# Generated by Django 5.2.16 on 2026-08-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme_edu', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id_reco', models.AutoField(primary_key=True, serialize=False)),
                ('date_generation', models.DateTimeField(auto_now=True)),
                ('cluster', models.IntegerField(blank=True, null=True)),
                ('profilApp', models.CharField(blank=True, choices=[('debutant', 'Débutant'), ('moyen', 'Moyen'), ('excellent', 'Excellent')], max_length=20, null=True)),
                ('identifiant', models.CharField(max_length=64, unique=True)),
                ('source', models.CharField(choices=[('oulad', 'OULAD (validation externe)'), ('plateforme', 'Plateforme (données réelles)')], default='oulad', max_length=20)),
                ('nb_interactions', models.IntegerField(default=0)),
                ('score_moyen', models.FloatField(blank=True, null=True)),
                ('ponctualite_moyenne', models.FloatField(blank=True, null=True)),
                ('charge_travail', models.FloatField(blank=True, null=True)),
                ('nb_tentatives_precedentes', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['profilApp', '-nb_interactions'],
            },
        ),
    ]
